### ISSUE TITLE
BitmapFont does not render correctly when using texture atlases with multiple resolutions

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL_BitmapFont#3]

**Comment by bp74** [comment]
Okay that's bad. Could you please send me a BitmapFont with multiple resolutions? Thanks!

**Comment by mnordine** [comment]
I did find a bit of a workaround. [Shoebox](https://renderhjs.net/shoebox/) has a feature that outputs 2 .fnt files for a given image (@1x, @2x). I manually load the .fnt file corresponding to `StageXL.bitmapDataLoadOptions.pixelRatios.last.toInt()`. After that, it renders at both resolutions, but the spacing is way too wide between chars on @2x. So I did this little hack and that seems to work decent. I just added a divisor for `xadvance` that I can manually set

https://github.com/mnordine/StageXL_BitmapFont/commit/a177f56c054b9942b546e218dfba89dd38088217

**Comment by bp74** [comment]
I just committed a new change where the pixel ratio is taken into account when loading a bitmap font. Please give it a try.

Btw. the example you sent me had another problem too. The FNT file was from the pixelRatio=2 image, but you defined your ResourceManger like this:

    final resources = new ResourceManager()
      ..addTextureAtlas('atlas', 'images/assets@1x.json')
      ..addTextFile('fredoka', 'images/fredoka.fnt');

This is a problem because you define the TextureAtlas where the BitmapFont image is stored with pixelRatio=1, but the FNT file is pixelRatio = 2. This does not match and you will get crazy result. You have to define both resources with the same pixelRatio like this:

    final resources = new ResourceManager() 
      ..addTextureAtlas('atlas', 'images/assets@2x.json')
      ..addTextFile('fredoka', 'images/fredoka.fnt');

Now both resources uses a pixelRatio of 2.0. If your screen has a pixelRatio of 1.0, both resources can be multiplied by 0.5 to get the correct pixel ratio of 1.0.

**Comment by bp74** [comment]
And another hint regarding your example:

Lets take a look at the letter 'A' in the FNT file:
char id=65 x=27 y=214 width=33 height=33 xoffset=1 yoffset=2 xadvance=34 page=0 chnl=15

Since the FNT file is designed for pixelRatio = 2 we have to multiply all coordinates by 0.5 to get to the coordinates for pixelRatio = 1. This is a problem because 27 * 0.5 = 13.5 which need to be rounded to 14 to get the correct pixel on the texture of the BitmapFont for pixelRatio = 1.

You would need to generate the FNT in a  clever way where the coordinates for all pixelRatios are a whole number like 13, but not 13.5). Hope this help!

**Comment by bp74** [comment]
Important Update!!!! I just reverted my commit and i will try to come up with something better.

I was reading lots of articles where people are talking about BitmapFonts and hidpi scaling. It is considered a bad idea to use the typical @1x and @2x approach, because it is very hard to get the spacing and scaling correct. For example Littera (http://kvazars.com/littera) provides the feature to export at different scale, but in this case you also get different FNT files for each scaling. This is probably the right thing to do.

I will keep you posted ....

**Comment by mnordine** [comment]
Yes Bernhard, not sure if you read my post above, but I did indeed generate 2 .fnt files.

**Comment by bp74** [comment]
i was reading your comment but i did not fully understand what you are saying because i was already working with your example where this was not the case.

**Comment by mnordine** [comment]
Sorry I wasn't more clear on that.

**Comment by bp74** [comment]
No problem, i thought my first approach should work okay but i was stupid :)

**Comment by bp74** [comment]
I've started an experimental branch for hidpi support:
https://github.com/bp74/StageXL_BitmapFont/tree/hidpi

This is work in progress, currently only loading the font directly from the font file works.

**Comment by bp74** [comment]
Now it also works with fonts loaded from BitmapData or TextureAtlas. 

First let's take a look how to load a hidpi BitmapFont directly from the file:

    var bitmapFont = await BitmapFont.load("font/font@1x.fnt");

And if you are working with TextureAtlases or BitmapDatas you can do it like this:

    var resourceManager = new ResourceManager();
    resourceManager.addBitmapData("fontPng", "font/font@1x.png");
    resourceManager.addTextFile("font@1", "font/font@1x.fnt");
    resourceManager.addTextFile("font@2", "font/font@2x.fnt");
    resourceManager.addTextFile("font@3", "font/font@3x.fnt");
    await resourceManager.load();

    var fontBitmapData = resourceManager.getBitmapData("fontPng");
    var fontPixelRatio = fontBitmapData.renderTextureQuad.pixelRatio.toStringAsFixed(0);
    var fontDefinition = resourceManager.getTextFile("font@$fontPixelRatio");
    var bitmapFont = await BitmapFont.fromBitmapData(fontBitmapData, fontDefinition);

The BitmapData (or TextureAtlas) is loaded with the optimal PixelRatio. The text file don't know nothing about pixel ratios, therefore we have to load them all. Later we create the BitmapFont dynamically from the loaded PNG file and one of the font definition files.

**Comment by mnordine** [comment]
Interesting, everything now works, but I'm getting extra spacing on @2x, unless I divide `xadvance` by pixel ratio.

```dart
import 'dart:html' as html;
import 'package:stagexl/stagexl.dart';
import 'package:stagexl_bitmapfont/stagexl_bitmapfont.dart';

main() async
{
  final options = new StageOptions()..backgroundColor = Color.Black;

  final canvas = html.querySelector('#stage');
  final stage = new Stage(canvas, width: 1280, height: 800, options: options);

  new RenderLoop()..addStage(stage);

  final resources = new ResourceManager()
    ..addTextureAtlas('atlas', 'images/assets@1x.json')
    ..addTextFile('fredoka@1', 'images/fredoka@1x.fnt')
    ..addTextFile('fredoka@2', 'images/fredoka@2x.fnt');

  await resources.load();

  final atlas = resources.getTextureAtlas('atlas');

  // Add background
  final bmd = atlas.getBitmapData('popup_bg');
  new Bitmap(bmd)..addTo(stage);

  final ratio = atlas.pixelRatio.toInt();
  final textFile = resources.getTextFile('fredoka@${ratio}');

  final font = await BitmapFont.fromTextureAtlas(atlas, '', textFile);

  new BitmapText(font)
    ..x = 150
    ..y = 200
    ..text = 'hello world\nhi there'
    ..addTo(stage);
}
```

@2x results in:

![hello](https://user-images.githubusercontent.com/1924573/27229696-f34c2000-5282-11e7-977f-83fdfcea96af.PNG)

@1x results in roughly what I'd expect:
![hello 1x](https://user-images.githubusercontent.com/1924573/27229968-07c16d78-5284-11e7-9087-53c62ed89301.PNG)

**Comment by bp74** [comment]
Please send me the files by mail so i can take a look at it, thanks!

**Comment by mnordine** [comment]
My mistake! I did not merge your changes into my fork before testing, sorry. After the merge, it looks good! Going to do more tests...

**Comment by bp74** [comment]
Awesome!

**Comment by mnordine** [comment]
Just updated my application and everything looks good!

**Comment by bp74** [comment]
Happy to hear that! Before i can publish this on Pub i have to update StageXL too, but i want to do some other things first. So hope you don't mind if we will release this a little bit later.

**Comment by mnordine** [comment]
No prob.

**Comment by mnordine** [comment]
I also like that you removed the duplicate logic in the atlas and bitmap loaders, :)

**Comment by bp74** [comment]
Yes i like this too, maybe we can improve it even more so the user can change the way how we decide which pixel ratio is actually loaded. This may become useful for you too. But no promises for now :)

**Comment by mnordine** [comment]
You are stingy with your promises, 😝
